blob_analysis: blob_demo.o blob_filter.o window.o post_process.o
	g++ -o blob_analysis blob_demo.o blob_filter.o window.o \
	post_process.o -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lopencv_hal

clean:
	rm -f *.o *.out *~ blob_analysis sample_image.jpg TAGS *.bmp *.png

tags:
	find . -name '*.cpp' -o -name '*.h' -o -name '*.c' | xargs etags --append
